#!/bin/sh

DEVEL="development"
VERSION="ncoh155"
NUMVER="1.5.5"

mkdir ~/www/download/$DEVEL/$NUMVER
make dist
#make distsmall
#make distbot
#make distpic
#make distutils
#make disttzinfo
./copy $VERSION $DEVEL/$NUMVER dist
#./copy $VERSION $DEVEL/$NUMVER distsmall
#./copy $VERSION $DEVEL/$NUMVER distbot
#./copy $VERSION $DEVEL/$NUMVER distpic
#./copy $VERSION $DEVEL/$NUMVER distutils
#./copy $VERSION $DEVEL/$NUMVER disttzinfo

./copydocs
mv ~/www/download/LATEST_DEVEL* ~/www/download/LATEST_DEVEL_IS_$NUMVER
mv ~/www/download/$DEVEL/LATEST_DEVEL* ~/www/download/$DEVEL/LATEST_DEVEL_IS_$NUMVER

